# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # e.g. install dependencies, run tests
        apt-get update && apt-get install -y python3 python3-pip && \
        pip3 install -r requirements.txt  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/market-stream-consumer'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/market-stream-consumer'

images:
  - 'gcr.io/$PROJECT_ID/market-stream-consumer'
